language: cpp
compiler: gcc

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-10
      - g++-10
      - lcov

script:
  - export CC=gcc-7
  - export CXX=g++-7
  - cmake --version
  - cmake -B linux 
  - cmake  --build . --target neat
