name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: make directorys
      run: mkdir build; cd build
    - name: cmake
      run: cmake .. -G "Unix Makefiles"
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
